#!/bin/bash
#SBATCH -N 4
#SBATCH -C cpu
#SBATCH --qos=debug
#SBATCH -J upctest 
#SBATCH --ntasks-per-node=32
#SBATCH -t 00:05:00
export UPCXX_SEGMENT_MB=1024
export GASNET_MAX_SEGSIZE=4G

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun ./fft_upcpp 

#srun ./main_fftw

###salloc -N 4 -C cpu --qos=debug -J upctest --ntasks-per-node=64 -t 00:05:00  --account=m4341